import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
// import "@/app/global.css";
import Navbar from "@/components/Navbar/Navbar";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Omentex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
       
        {children}
        </body>
    </html>
  );
}
